TYPE DUT_OUTPUTS :
STRUCT
	Conv1_cmd_fwd : BIT; //Run conveyor forward
	conv2_cmd_fwd : BIT; //Run conveyor forward
	Conv1_cmd_bwd : BIT; //Run conveyor backward
	conv2_cmd_bwd : BIT; //Run conveyor backward
	SPARE_OUTPUT_01 : BIT; //Spare bit
	SPARE_OUTPUT_02 : BIT; //Spare bit
	SPARE_OUTPUT_03 : BIT; //Spare bit
	SPARE_OUTPUT_04 : BIT; //Spare bit
	em1_cmd_emit : BIT; //Trigger item spawn
	destroyer_cmd_on : BIT; //Enable destroyer
	SPARE_OUTPUT_05 : BIT; //Spare bit
	SPARE_OUTPUT_06 : BIT; //Spare bit
	SPARE_OUTPUT_07 : BIT; //Spare bit
	SPARE_OUTPUT_08 : BIT; //Spare bit
	SPARE_OUTPUT_09 : BIT; //Spare bit
	SPARE_OUTPUT_10 : BIT; //Spare bit
	RDS1_cmd_left : BIT; //Command divert left (belt forward)
	RDS1_cmd_right : BIT; //Command divert right (belt backward)
	SPARE_OUTPUT_11 : BIT; //Spare bit
	SPARE_OUTPUT_12 : BIT; //Spare bit
	SPARE_OUTPUT_13 : BIT; //Spare bit
	SPARE_OUTPUT_14 : BIT; //Spare bit
	SPARE_OUTPUT_15 : BIT; //Spare bit
	SPARE_OUTPUT_16 : BIT; //Spare bit
	SPARE_OUTPUT_17 : BIT; //Spare bit
	SPARE_OUTPUT_18 : BIT; //Spare bit
	SPARE_OUTPUT_19 : BIT; //Spare bit
	SPARE_OUTPUT_20 : BIT; //Spare bit
	SPARE_OUTPUT_21 : BIT; //Spare bit
	SPARE_OUTPUT_22 : BIT; //Spare bit
	SPARE_OUTPUT_23 : BIT; //Spare bit
	SPARE_OUTPUT_24 : BIT; //Spare bit
	SPARE_OUTPUT_25 : BIT; //Spare bit
	SPARE_OUTPUT_26 : BIT; //Spare bit




END_STRUCT
END_TYPE