TYPE DUT_INPUTS :
STRUCT
TWB1_fb_pulse : BIT; //Pulse position sensor (Width: 50mm)
TWB2_fb_pulse : BIT; //Pulse position sensor (Width: 50mm)
TWB3_fb_pulse : BIT; //Pulse position sensor (Width: 50mm)
TWB4_fb_pulse : BIT; //Pulse position sensor (Width: 50mm)
SPARE_INPUT_01 : BIT; //Spare bit
SPARE_INPUT_02 : BIT; //Spare bit
SPARE_INPUT_03 : BIT; //Spare bit
SPARE_INPUT_04 : BIT; //Spare bit
TWB1_fb_ps1 : BIT; //Sensor array TWB1 PS1 feedback (Position: 600mm)
TWB2_fb_ps1 : BIT; //Sensor array TWB2 PS1 feedback (Position: 3400mm)
TWB2_fb_ps2 : BIT; //Sensor array TWB2 PS2 feedback (Position: 600mm)
TWB3_fb_ps1 : BIT; //Sensor array TWB3 PS1 feedback (Position: 7400mm)
TWB3_fb_ps2 : BIT; //Sensor array TWB3 PS2 feedback (Position: 600mm)
TWB4_fb_ps1 : BIT; //Sensor array TWB4 PS1 feedback (Position: 1400mm)
SPARE_INPUT_05 : BIT; //Spare bit
SPARE_INPUT_06 : BIT; //Spare bit
Rise1_fb_rised : BIT; //Rising divert at raised position
Rise1_fb_initial : BIT; //Rising divert at initial position
SPARE_INPUT_07 : BIT; //Spare bit
SPARE_INPUT_08 : BIT; //Spare bit
SPARE_INPUT_09 : BIT; //Spare bit
SPARE_INPUT_10 : BIT; //Spare bit
SPARE_INPUT_11 : BIT; //Spare bit
SPARE_INPUT_12 : BIT; //Spare bit
SPARE_INPUT_13 : BIT; //Spare bit
SPARE_INPUT_14 : BIT; //Spare bit
SPARE_INPUT_15 : BIT; //Spare bit
SPARE_INPUT_16 : BIT; //Spare bit
SPARE_INPUT_17 : BIT; //Spare bit
SPARE_INPUT_18 : BIT; //Spare bit






END_STRUCT
END_TYPE