TYPE DUT_INPUTS :
STRUCT
	Conv1_fb_pulse : BIT; //Pulse position sensor
	conv2_fb_pulse : BIT; //Pulse position sensor
	SPARE_INPUT_01 : BIT; //Spare bit
	SPARE_INPUT_02 : BIT; //Spare bit
	SPARE_INPUT_03 : BIT; //Spare bit
	SPARE_INPUT_04 : BIT; //Spare bit
	SPARE_INPUT_05 : BIT; //Spare bit
	SPARE_INPUT_06 : BIT; //Spare bit
	PS1_fb : BIT; //Sensor feedback signal
	PS2_fb : BIT; //Sensor feedback signal
	SPARE_INPUT_07 : BIT; //Spare bit
	SPARE_INPUT_08 : BIT; //Spare bit
	SPARE_INPUT_09 : BIT; //Spare bit
	SPARE_INPUT_10 : BIT; //Spare bit
	SPARE_INPUT_11 : BIT; //Spare bit
	SPARE_INPUT_12 : BIT; //Spare bit
	RDS1_fb_rised : BIT; //Rising divert at raised position
	RDS1_fb_initial : BIT; //Rising divert at initial position
	SPARE_INPUT_13 : BIT; //Spare bit
	SPARE_INPUT_14 : BIT; //Spare bit
	SPARE_INPUT_15 : BIT; //Spare bit
	SPARE_INPUT_16 : BIT; //Spare bit
	SPARE_INPUT_17 : BIT; //Spare bit
	SPARE_INPUT_18 : BIT; //Spare bit
	SPARE_INPUT_19 : BIT; //Spare bit
	SPARE_INPUT_20 : BIT; //Spare bit
	SPARE_INPUT_21 : BIT; //Spare bit
	SPARE_INPUT_22 : BIT; //Spare bit
	SPARE_INPUT_23 : BIT; //Spare bit
	SPARE_INPUT_24 : BIT; //Spare bit
	SPARE_INPUT_25 : BIT; //Spare bit
	SPARE_INPUT_26 : BIT; //Spare bit
	SPARE_INPUT_27 : BIT; //Spare bit
	SPARE_INPUT_28 : BIT; //Spare bit
	SPARE_INPUT_29 : BIT; //Spare bit
	SPARE_INPUT_30 : BIT; //Spare bit


END_STRUCT
END_TYPE